#!/bin/sh

# Automatically adds branch name and branch description to every commit message.
BRANCH_NAME=$(git branch | grep '^\*' |  cut -c 3-)
BRANCH_NAME_FORMATTED=$(echo $BRANCH_NAME | cut -d '/' -f2 | sed -e 's/^[[:space:]]*//' -e 's/[[:space:]]*$//')
BRANCH_DESCR=$(git config branch."$NAME".description)
COMMIT_MSG=$(cat "$1")

# Add branch name if branch dont have /
ADD_NON_FEATURE_BRANCHES=false
ADD_BRANCH_DESCR=false

echo "" > "$1"

if [[ $BRANCH_NAME =~ "/" ]] || [[ "$ADD_NON_FEATURE_BRANCHES" = true ]]; then
  echo "[$BRANCH_NAME_FORMATTED]" >> "$1"
fi


if [[ -n "$BRANCH_DESCR" ]] && [[ "$ADD_BRANCH_DESCR" = true ]]; then
  echo "[$BRANCH_DESCR]" >> "$1"
fi


# Add project version if branch is DEV or MASTER
VERSION_BRANCHES=("dev", "master")

PROJECT_VERSION=$(gradle properties | grep ^version | cut -c 10-)
if [[ "${VERSION_BRANCHES[@]}" =~ "$BRANCH_NAME" ]]; then
  echo "[$PROJECT_VERSION]" >> "$1"
fi


echo "$COMMIT_MSG" >> "$1"